import type { Metadata } from "next";
import "./globals.css";
import ToastexContext from "./context/ToastexContext";
import SignOut from "@/components/SignOut";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToastexContext />
          {children}
          <SignOut />
        </SessionProvider>
      </body>
    </html>
  );
}
